В этом задании вам предлагается начать разбираться с задачей анализа тональности отзывов на примере сентимент-анализа отзывов на фильмы.

Мы будем использовать стандартный датасет из nltk, уже возникавший в одном из примеров в предыдущих курсах. 

Для того, чтобы импортировать необходимый модуль, напишите:  
<br><center><code>from nltk.corpus import movie_reviews</code></center></br>

Чтобы получить id-шники негативных и позитивных отзывов:  
<br><center><code>negids = movie_reviews.fileids('neg')
posids = movie_reviews.fileids('pos')</code></center></br>
  
Чтобы получить список негативных отзывов:   
<br><center><code>negfeats = [movie_reviews.words(fileids=[f]) for f in negids]</code></center></br>


**Инструкция по выполнению**

В некоторых пунктах нужно получить ответ - число или строку, которые будет нужно набирать в текстовых файлах и прикреплять в ответах на вопросы. Десятичные дроби записывайте через точку.

1. Создайте список из текстов всех имеющихся отзывов, а также список с классами, которые будет использовать ваш классификатор - 0 для негативных отзывов и 1 для позитивных.


2. Подсчитайте количество отзывов в выборке.


3. Подсчитайте долю класса 1 в выборке.


4. Импортируйте CountVectorizer из sklearn.feature_extraction.text. Попробуйте использовать его с настройками по умолчанию для того, чтобы получить признаковое представление каждого текста. Скорее всего, попытка не увенчается успехом. Разберитесь, в чем причина, и добейтесь того, чтобы метод fit_transform у CountVectorizer успешно отрабатывал. Подсчитайте количество признаков в CountVectorizer. Никакой предварительной обработки текста (удаление стоп-слов, нормализация слов) на этом шаге делать не надо, в качестве признаков должны использоваться частоты слов.


5. Соберите pipeline из CountVectorizer и LogisticRegression c настройками по-умолчанию и с помощью cross_val_score (также со стандартными настройками) оцените получаемое "из коробки" качество по accuracy.


6. Аналогично accuracy, оцените качество по ROC AUC.


7. Обучите логистическую регрессию на всей доступной вам выборке и выведите 5 наиболее важных для модели признаков (подумайте, какие именно признаки стоит считать такими). Вам могут пригодиться метод get_feature_names() или поле vocabulary_ у класса CountVectorizer.

---
---

Вопросы:
1. Количество отзывов во всей выборке
2. Доля позитивных отзывов
3. Количество признаков со стандартными настройками
4. Accuracy в кросс-валидации
5. ROC AUC в кросс-валидации
6. Запишите соответствующие двум самым важным для модели признакам слова из словаря через пробел

In [55]:
import nltk
# nltk.download("movie_reviews")
from nltk.corpus import movie_reviews
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score

In [3]:
def write_ans(file_name, *args):
    with open(file_name, "w") as file:
        file.write(" ".join(map(str, args)))

In [130]:
" ".join(map(str, [1, 2, 3]))

'1 2 3'

In [21]:
negids = movie_reviews.fileids('neg')
posids = movie_reviews.fileids('pos')

In [25]:
# 1. Количество отзывов во всей выборке
ans_1 = len(negids) + len(posids)
write_ans("ans_1.txt", ans_1)

In [31]:
# 2. Доля позитивных отзывов
write_ans("ans_2.txt", len(posids) / ans_1)

In [33]:
clf = CountVectorizer()

In [41]:
negfeats = [" ". join(movie_reviews.words(fileids=[f])) for f in negids]
posfeats = [" ". join(movie_reviews.words(fileids=[f])) for f in posids]

In [43]:
x = negfeats + posfeats
len(x)

2000

In [46]:
y = [0] * 1000 + [1] * 1000
len(y)

2000

In [47]:
clf.fit(x, y)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

In [52]:
# 3.Количество признаков со стандартными настройками
ans_3 = len(clf.get_feature_names())
write_ans("ans_3.txt", ans_3)
print(ans_3)

39659


In [ ]:
# Pipeline([("vectorizer", CountVectorizer()), ("classifier", LogisticRegression())])


In [72]:
# 4
# Соберите pipeline из CountVectorizer и LogisticRegression c настройками по-умолчанию
# и с помощью cross_val_score (также со стандартными настройками)
# оцените получаемое "из коробки" качество по accuracy.

count = CountVectorizer()
log_reg = LogisticRegression()
pipe = Pipeline([('countvectorizer', count),
                 ('logisticregression', log_reg)])

In [119]:
res = cross_val_score(pipe, x, y, scoring="accuracy")
print(res)
write_ans("ans_4.txt", res.mean())

D:\Anaconda3\envs\py36_R\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
D:\Anaconda3\envs\py36_R\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


[0.81437126 0.84684685 0.84684685]


In [120]:
# 5. ROC AUC в кросс-валидации

res = cross_val_score(pipe, x, y, scoring="roc_auc")
write_ans("ans_5.txt", res.mean())
print(res)

D:\Anaconda3\envs\py36_R\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
D:\Anaconda3\envs\py36_R\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


[0.9006239  0.91283175 0.91887383]


In [88]:
# 6
# Запишите соответствующие двум самым важным для модели признакам слова из словаря через пробел

pipe.fit(x, y);


In [113]:
log_reg.coef_[0]

array([ 1.13388312e-02, -1.78986913e-02,  2.67552873e-06, ...,
       -7.15693483e-03,  3.78870960e-04, -1.40824162e-03])

In [126]:
features = sorted(
    list(
        zip(
            abs(log_reg.coef_[0]),
            count.get_feature_names()
            )
        ),
    reverse=True
)


In [127]:
features[:5]

[(0.7822542657559508, 'bad'),
 (0.6366239815648874, 'unfortunately'),
 (0.5928385063136231, 'worst'),
 (0.5560509781124982, 'fun'),
 (0.5081911925070863, 'waste')]

In [131]:
ans = [x[1] for x in features[:2]]
print(ans)
write_ans("ans_6.txt", *ans)

['bad', 'unfortunately']


In [122]:
coeffs = log_reg.coef_[0]
[count.get_feature_names()[list(coeffs).index(i)] for i in sorted(coeffs)[:5]]

['bad', 'unfortunately', 'worst', 'waste', 'nothing']