1. Выберите те наборы векторов, которые являются линейно независимыми (один вектор тоже считается набором).
 - (1,0), (0,1) (+)
 - (1, 0), (0, 1), (-1, 1) (-)
 - (1, 0) (+) ?
 - (1, 0), (1, 1) (+)

2. Чему равна манхэттенская норма вектора a = (-1, 2, -1)?
 - 4

3. Чему равно скалярное произведение векторов a=(1, 2, 3) и b=(-3, 1, 1)?
 - 2


4. В пространствах какой размерности можно выбрать k линейно независимых векторов?
 - k (+)
 - k-1 (-)
 - k+1 (+)

5. Какие из нижеприведенных команд корректно отработают и создадут вектор?
 - b = numpy.array(1, 2, 3, 4, 5, dtype=float) (-)
 - b = numpy.array([1, 2, 3, 4, 5], dtype=float) (+) 
 - c = numpy.array([False, False, True]) (+)
 - f = numpy.arange(1, 2, 0.3, dtype=float) (+)

In [13]:
import numpy
from scipy import spatial

In [8]:
b = numpy.array([1, 2, 3, 4, 5], dtype=float)
c = numpy.array([False, False, True])
f = numpy.arange(1, 2, 0.3, dtype=float)

6. Пусть даны два вектора a = numpy.array([6, 3, -5]) и b = numpy.array([-1, 0, 7]). Какая из следующих команд считает евклидово расстояние между этими векторами?
 - scipy.spatial.distance.cdist(a[numpy.newaxis, :], b[numpy.newaxis, :], metric='euclidean')
   $$ 14,213 $$

In [11]:
a = numpy.array([6, 3, -5]) 
b = numpy.array([-1, 0, 7])

In [20]:
print scipy.spatial.distance.cdist(a[numpy.newaxis, :], b[numpy.newaxis, :], metric='euclidean')
print numpy.linalg.norm(a, ord=2) - numpy.linalg.norm(b, ord=2)
# print scipy.spatial.distance.cdist(b, a, metric='euclidean')
print scipy.spatial.distance.cdist(a[:, numpy.newaxis], b[:, numpy.newaxis], metric='euclidean')

[[14.2126704]]
1.2955324534752801
[[ 7.  6.  1.]
 [ 4.  3.  4.]
 [ 4.  5. 12.]]


7. Пусть даны два вектора a = numpy.array([0, -1, 11]) и b = numpy.array([3, 7, 2]). Какие из следующих команд считают скалярное произведение этих векторов?
 - a * b (-)  
 - numpy.dot(a, b) / numpy.linalg.norm(a) / numpy.linalg.norm(b) (-)  
 - numpy.dot(a, b) (+)  
 - b.dot(a) (+)  

8. Пусть дан вектор a = numpy.array([8, 10, -1, 0, 0]). Какие из следующих команд преобразуют вектор a к вектор-столбцу?
 - a = a[numpy.newaxis, :] (-)  
 - a = a[:, numpy.newaxis] (+)  
 - a = a.reshape((1, 5)) (-)  
 - a = a.reshape((5, 1)) (+)  

In [21]:
a = numpy.array([8, 10, -1, 0, 0])

In [27]:
print a.shape
print a[numpy.newaxis, :].shape
print  a[:, numpy.newaxis].shape
print a.reshape((1, 5)).shape
print a.reshape((5, 1)).shape

(5L,)
(1L, 5L)
(5L, 1L)
(1L, 5L)
(5L, 1L)
