In [1]:
import numpy as np

1. Выберите матрицу, которая подойдет для описания левой части системы из двух уравнений с неизвестными x и z:  

$$ \begin{equation*}
 \begin{cases}
   2x + 5z = 1, 
   \\
   x - z = 2
 \end{cases}
\end{equation*} $$
  
  -  $  \begin{pmatrix}
  3& 5\\
  1& -1
\end{pmatrix} $


2. Чему равен ранг следующей матрицы?  
$$ \begin{pmatrix}
  1& 0& 1\\
  1& 2& 2
\end{pmatrix} $$
 -  2


3. Сколько решений может иметь система линейных уравнений?
 - Ни одного (+)
 - Одно  (+)
 - Больше одного, но конечное число  (-)
 - Бесконечное число (+)   

4. К каким классам относится следующая матрица?
$$ \begin{pmatrix}
  1& 2\\
  1& 2
\end{pmatrix} $$
 - Диагональная
 - Ортогональная
 - Симметричная

5. Какое из следующих утверждений правильно характеризует собственные векторы?  
 - Собственный вектор матрицы задает направление, вдоль которого соответствующее линейное преобразование действует как сжатие или растяжение

6. Какие из нижеприведенных команд корректно отработают и создадут двумерный массив? 
 - e = np.arange(1, 13, 2).reshape((3, 2)) (+)  
 - d = np.ones((10, 10)) (+)  
 - b = np.eye(2, 3) (+)  
 - c = np.eye((4, 5)) (-)  
 - a = np.array([4, 3, 2], [2, 9, 1], [3, 1, 9]) (-)  

7. Пусть создан массив с помощью команды a = np.eye(4, 5). Что вернет операция a[[0, 3], [1, 3]]?  
 - Одномерный массив с числами 0 и 1.

In [10]:
a = np.eye(4, 5)
print a
print a[[0, 3], [1, 3]]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]
[0. 1.]
