In [2]:
import numpy as np
import pandas as pd
import itertools
from scipy import stats

from statsmodels.stats.weightstats import zconfint
from statsmodels.stats.weightstats import *

### 1
Какую из этих гипотез нельзя проверить с помощью критерия знаков?


- Гипотеза о равенстве средних в двух независимых выборках $\large \checkmark$


---
---
### 2
Какую из этих гипотез о средних двух независимых выборок проверяет критерий Манна-Уитни?


- $H_0:F_{X_1}(x)=F_{X_2}(x)$ против $H_1:F_{X_1}(x)=F_{X_2}(x+Δ),Δ<\ne>0$


---
---
### 3
У вас есть две регрессионные модели и двадцать наборов данных. На обучающей подвыборке каждого набора вы настраиваете обе модели и считаете среднеквадратичную ошибку на тестовой подвыборке набора. 

**Какими из этих критериев не стоит проверять гипотезу о том, что среднее качество регрессионных моделей одинаково?**

https://www.coursera.org/learn/stats-for-data-analysis/discussions/weeks/2/threads/UjhF025PEeaeEw4INb6PhQ

- Перестановочный критерий со статистикой $T=\sum\limits_{i=1}^n \left(X_{1i}-X_{2i}\right) $ и $2^n$ вариантами расстановки знаков у попарных разностей 



- Критерий знаковых рангов (-, можно использовать для зависимых выборок)


- Критерий Стьюдента для двух независимых выборок **( + выборки зависимые)**


- Критерий знаков (- можно использовать критерий знаков для связанных выборок)


- Перестановочный критерий со статистикой $T=\frac1{n}\sum\limits_{i=1}^n X_{1i}-\frac1{n}\sum\limits_{i=1}^n X_{2i}$ вариантами расстановки объектов по выборкам **(+ этот вариант для независимых выборок)**


- Критерий Манна-Уитни **(+ данный критерий для независимых выборок)**

---
---
### 4
Давайте вернёмся к данным выживаемости пациентов с лейкоцитарной лимфомой из видео про критерий знаков:

$$ 49, 58, 75, 110, 112, 132, 151, 276, 281, 362^*$$
 

Измерено остаточное время жизни с момента начала наблюдения (в неделях); звёздочка обозначает цензурирование сверху — исследование длилось 7 лет, и остаточное время жизни одного пациента, который дожил до конца наблюдения, неизвестно.

Поскольку цензурировано только одно наблюдение, для проверки гипотезы 

- $H_0 : medX=200 $

на этих данных можно использовать критерий знаковых рангов — можно считать, что время дожития последнего пациента в точности равно 362, на ранг этого наблюдения это никак не повлияет.

Критерием знаковых рангов проверьте эту гипотезу против двусторонней альтернативы, введите достигаемый уровень значимости, округлённый до четырёх знаков после десятичной точки.


In [3]:
from scipy import stats

values = np.array([49, 58, 75, 110, 112, 132, 151, 276, 281, 362])

#### Критерий знаковых рангов Уилкоксона

$H_0\colon med\left(X_1\right)=0,$

$H_1\colon med\left(X_1\right)\neq0$

In [4]:
round(stats.wilcoxon(values - 200)[1], 4)

0.2845

---
---
### 5
В ходе исследования влияния лесозаготовки на биоразнообразие лесов острова Борнео собраны данные о количестве видов деревьев в 12 лесах, где вырубка не ведётся:

$$22, 22, 15, 13, 19, 19, 18, 20, 21, 13, 13, 15$$

и в 9 лесах, где идёт вырубка:

$$ 17, 18, 18, 15, 12, 4, 14, 15, 10$$

Проверьте гипотезу о 

- $H_0:$ равенстве среднего количества видов в двух типах лесов


- против односторонней альтернативы о снижении биоразнообразия в вырубаемых лесах. 

Используйте ранговый критерий. Чему равен достигаемый уровень значимости? Округлите до четырёх знаков после десятичной точки.

#### Ранговый критерий Манна-Уитни
$H_0\colon F_{X_1}(x) = F_{X_2}(x)$

$H_1\colon F_{X_1}(x) = F_{X_2}(x + \Delta), \Delta\neq 0$

In [5]:
forest_1 = np.array([22, 22, 15, 13, 19, 19, 18, 20, 21, 13, 13, 15])
forest_2 = np.array([17, 18, 18, 15, 12, 4, 14, 15, 10])

forest_1.mean(), forest_2.mean()

(17.5, 13.666666666666666)

In [6]:
round(stats.mannwhitneyu(forest_1, forest_2, alternative="greater")[1], 4)

0.029

---
---
### 6
28 января 1986 года космический шаттл "Челленджер" взорвался при взлёте. Семь астронавтов, находившихся на борту, погибли. В ходе расследования причин катастрофы основной версией была неполадка с резиновыми уплотнительными кольцами в соединении с ракетными ускорителями. Для 23 предшествовавших катастрофе полётов "Челленджера" известны температура воздуха и появление повреждений хотя бы у одного из уплотнительных колец.

С помощью бутстрепа постройте 95% доверительный интервал для разности средних температур воздуха при запусках, когда уплотнительные кольца повреждались, и запусках, когда повреждений не было. Чему равна его ближайшая к нулю граница? Округлите до четырёх знаков после запятой.

Чтобы получить в точности такой же доверительный интервал, как у нас:

1. установите random seed = 0 перед первым вызовом функции get_bootstrap_samples, **один раз**


2. сделайте по 1000 псевдовыборок из каждой выборки.

In [7]:
def get_bootstrap_samples(data, num=1000):
    i = np.random.randint(0, len(data), (num, len(data)))
    return data[i]

In [8]:
def stat_intervals(stat, alpha=0.05):
    boundaries = np.percentile(stat, [100 * alpha / 2, 100 * (1 - alpha / 2)])
    return boundaries

In [9]:
df = pd.read_csv("challenger.txt", sep="\t").drop("Unnamed: 0", axis=1)
df.head()

Temperature  Incident
0         18.9         0
1         21.1         1
2         20.6         0
3         20.0         0
4         19.4         0

In [10]:
crush = df[df.Incident == 1].Temperature.values
not_crush = df[df.Incident == 0].Temperature.values

In [11]:
crush

array([21.1, 13.9, 17.2, 21.1, 11.7, 23.9, 14.4])

In [12]:
not_crush

array([18.9, 20.6, 20. , 19.4, 22.2, 22.8, 21.1, 25.6, 19.4, 19.4, 23.9,
       21.1, 27.2, 24.4, 26.1, 24.4])

In [13]:
np.random.seed(0)
crush_mean = np.mean(get_bootstrap_samples(crush))
not_crush_mean = np.mean(get_bootstrap_samples(not_crush))



In [14]:
crush_mean, not_crush_mean

(17.684885714285713, 22.2920625)

In [15]:
res = stat_intervals(crush_mean - not_crush)
res

array([-9.10261429, -1.40261429])

In [16]:
round(res[1], 4)

-1.4026

In [17]:
-1.4504

-1.4504

---
---
### 7
На данных предыдущей задачи проверьте гипотезу об одинаковой средней температуре воздуха в дни, когда уплотнительный кольца повреждались, и дни, когда повреждений не было. Используйте перестановочный критерий и двустороннюю альтернативу. Чему равен достигаемый уровень значимости? Округлите до четырёх знаков после десятичной точки.

Чтобы получить такое же значение, как мы:

1. установите random seed = 0;


2. возьмите 10000 перестановок.


In [18]:
def permutation_t_stat_ind(sample1, sample2):
    return np.mean(sample1) - np.mean(sample2)

In [19]:
def get_random_combinations(n1, n2, max_combinations):
    index = list(range(n1 + n2))
    indices = set([tuple(index)])
    for i in range(max_combinations - 1):
        np.random.shuffle(index)
        indices.add(tuple(index))
    return [(index[:n1], index[n1:]) for index in indices]

In [20]:
def permutation_zero_dist_ind(sample1, sample2, max_combinations=None):
    joined_sample = np.hstack((sample1, sample2))
    n1 = len(sample1)
    n = len(joined_sample)
    
    if max_combinations:
        indices = get_random_combinations(n1, len(sample2), max_combinations)
    else:
        indices = [(list(index), filter(lambda i: i not in index, range(n))) \
                    for index in itertools.combinations(range(n), n1)]
    
    distr = [joined_sample[list(i[0])].mean() - joined_sample[list(i[1])].mean() \
             for i in indices]
    return distr

In [21]:
def permutation_test(sample, mean, max_permutations = None, alternative='two-sided'):
    if alternative not in ('two-sided', 'less', 'greater'):
        raise ValueError("alternative not recognized\n"
                         "should be 'two-sided', 'less' or 'greater'")
    
    t_stat = permutation_t_stat_ind(sample, mean)
    
    zero_distr = permutation_zero_dist_ind(sample, mean, max_permutations)
    
    if alternative == 'two-sided':
        return sum([1. if abs(x) >= abs(t_stat) else 0. for x in zero_distr]) / len(zero_distr)
    
    if alternative == 'less':
        return sum([1. if x <= t_stat else 0. for x in zero_distr]) / len(zero_distr)

    if alternative == 'greater':
        return sum([1. if x >= t_stat else 0. for x in zero_distr]) / len(zero_distr)

In [22]:
crush, not_crush

(array([21.1, 13.9, 17.2, 21.1, 11.7, 23.9, 14.4]),
 array([18.9, 20.6, 20. , 19.4, 22.2, 22.8, 21.1, 25.6, 19.4, 19.4, 23.9,
        21.1, 27.2, 24.4, 26.1, 24.4]))

In [23]:
np.random.seed(0)
permutation_test(not_crush, crush, max_permutations=10000)

0.007