In [1]:
import numpy as np

#### Генерация случайной матрицы

Сгенерируйте матрицу, состоящую из 1000 строк и 50 столбцов, элементы которой являются случайными из нормального распределения N(1,100).

Функция для генерации чисел из нормального распределения: np.random.normal

Параметры:
 - loc: среднее нормального распределения (в нашем случае 1)
 - scale: стандартное отклонение нормального распределения (в нашем случае 10)
 - size: размер матрицы (в нашем случае (1000, 50))

In [4]:
X = np.random.normal(loc=1, scale=10, size=(100, 50))
X[:1]

array([[  7.21358182,  -3.91320161,  -1.79997609, -12.86542696,
          2.46320271,   6.17891631,   1.15227932,   2.47087933,
          8.11750624,  -4.84459954,  -3.42530848,   4.03745266,
          5.13718326,  -4.5958427 ,  -6.25757848,   5.45442466,
         -2.79898225,  -0.43516047,   9.03409018,   2.949198  ,
          6.73124012,   8.88170372, -15.21170594,  11.23486065,
        -12.56601912,   3.30513686,   1.19644045,  -3.95884719,
         -8.80034147,   0.58023004, -16.99933795,   7.53980524,
         13.17585103,   3.69090766,  -1.94503742,  -6.73284807,
         18.40985149,   4.58428382,  -3.39259223,  15.2431128 ,
          2.67808376,   2.28236664,  13.61987705,   2.01888515,
         12.98472021,   6.37644892,  -0.44406445,  12.89118968,
         11.37180909,  -8.59501902]])

#### Нормировка матрицы

Произведите нормировку матрицы из предыдущего задания: вычтите из каждого столбца его среднее значение, а затем поделите на его стандартное отклонение.

Функция для вычисления среднего: np.mean

Функция для вычисления стандартного отклонения: np.std

Первый параметр — матрица, для которой производятся вычисления. Также полезным будет параметр axis, который указывает, по какому измерению вычисляются среднее и стандартное отклонение (если axis=0, то по столбцам, если axis=1, то по строкам; если его не указывать, то данные величины будут вычислены по всей матрице).

In [9]:
means = np.mean(X, axis=0)
print(len(means))

stds = np.std(X, axis=0)
print(len(stds))

50
50


In [10]:
X_norm = (X - means) / stds
X_norm[:1]

array([[ 0.73800746, -0.53693229, -0.33394756, -1.47579996,  0.21331709,
         0.40725935,  0.06834701,  0.16342285,  0.7033988 , -0.44100871,
        -0.43383769,  0.40498965,  0.40009491, -0.56340861, -0.64107   ,
         0.66686165, -0.30969136, -0.04121279,  0.65176789,  0.25107281,
         0.57994429,  0.92684273, -1.76269868,  0.90887794, -1.27563559,
         0.37206861,  0.10716973, -0.54783185, -0.91684342, -0.02894537,
        -1.62751929,  0.74911194,  1.34011224,  0.12342595, -0.50876535,
        -0.93421392,  1.89624293,  0.42657759, -0.43753284,  1.22061794,
        -0.00646847,  0.22635521,  1.28303841,  0.19431892,  1.26918893,
         0.53985001, -0.22524358,  1.20292352,  1.09418638, -0.91757888]])

#### Операции над элементами матрицы

Выведите для заданной матрицы номера строк, сумма элементов в которых превосходит 10.

Функция для подсчета суммы: np.sum

Аргументы аналогичны функциям np.mean и np.std.

К матрицам можно применять логические операции, которые будут применяться поэлементно. Соответственно, результатом такой операции будет матрица такого же размера, в ячейках которой будет записано либо True, либо False. Индексы элементов со значением True можно получить с помощью функции np.nonzero.

In [17]:
np.array: Z = np.array([[4, 5, 0], 
             [1, 9, 3],              
             [5, 1, 1],
             [3, 3, 3], 
             [9, 9, 9], 
             [4, 7, 1]])
Z.shape

(6, 3)

In [18]:
res = np.sum(Z, axis=1)
res

array([ 9, 13,  7,  9, 27, 12])

In [19]:
np.nonzero( res > 10)  # indexes

(array([1, 4, 5], dtype=int64),)

In [23]:
res > 10

array([False,  True, False, False,  True,  True])

In [22]:
res[res > 10]  # values

array([13, 27, 12])

#### Объединение матриц

Сгенерируйте две единичные матрицы (т.е. с единицами на диагонали) размера 3x3. Соедините две матрицы в одну размера 6x3.

Функция для генерации единичной матрицы: np.eye

Аргумент: число строк (или, что эквивалентно, столбцов).

Функция для вертикальной стыковки матриц: np.vstack((A, B))

In [25]:
A = np.eye(3)
B = np.eye(3)
print(A)
print(B)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [26]:
np.vstack((A, B))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])