#### Загрузите датасеты digits и breast_cancer из sklearn.datasets

In [5]:
from sklearn.datasets import load_breast_cancer, load_digits

In [12]:
bc_data = load_breast_cancer().data
bc_target = load_breast_cancer().target

d_data = load_digits().data
d_target = load_digits().target

#### Выведите несколько строчек из обучающих выборок и посмотрите на признаки.

In [20]:
bc_data[:1]

array([[1.799e+01, 1.038e+01, 1.228e+02, 1.001e+03, 1.184e-01, 2.776e-01,
        3.001e-01, 1.471e-01, 2.419e-01, 7.871e-02, 1.095e+00, 9.053e-01,
        8.589e+00, 1.534e+02, 6.399e-03, 4.904e-02, 5.373e-02, 1.587e-02,
        3.003e-02, 6.193e-03, 2.538e+01, 1.733e+01, 1.846e+02, 2.019e+03,
        1.622e-01, 6.656e-01, 7.119e-01, 2.654e-01, 4.601e-01, 1.189e-01]])

In [19]:
d_data[:1]

array([[ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.,  0.,  0., 13., 15., 10.,
        15.,  5.,  0.,  0.,  3., 15.,  2.,  0., 11.,  8.,  0.,  0.,  4.,
        12.,  0.,  0.,  8.,  8.,  0.,  0.,  5.,  8.,  0.,  0.,  9.,  8.,
         0.,  0.,  4., 11.,  0.,  1., 12.,  7.,  0.,  0.,  2., 14.,  5.,
        10., 12.,  0.,  0.,  0.,  0.,  6., 13., 10.,  0.,  0.,  0.]])

In [23]:
bc_data.shape

(569, 30)

 С помощью sklearn.cross_validation.cross_val_score c настройками по умолчанию и вызова метода mean() у возвращаемого этой функцией numpy.ndarray, сравните качество работы наивных байесовских классификаторов на этих двух датасетах.
 
 Для сравнения предлагается использовать BernoulliNB, MultinomialNB и GaussianNB. Насколько полученные результаты согласуются с рекомендациями из лекций?

In [18]:
from sklearn.model_selection import cross_val_score
from sklearn.naive_bayes import BernoulliNB, MultinomialNB, GaussianNB

In [34]:
result = []
for data, y, title in ((bc_data, bc_target, "Breast"), (d_data, d_target, "Digits")):
    print(f"{title}: ")
    
    some = []
    for label, estimator in zip(("Bern", "Multi", "Gauss"),
                                (BernoulliNB(), MultinomialNB(), GaussianNB())):
        value = cross_val_score(estimator, data, y=y).mean()
        some.append(value)
        print(f"{label}:", round(value, 3))
    result.append(some)
    
    print()
        


Breast: 
Bern: 0.627
Multi: 0.895
Gauss: 0.937

Digits: 
Bern: 0.826
Multi: 0.871
Gauss: 0.819



D:\Anaconda3\envs\py36_R\lib\site-packages\sklearn\model_selection\_split.py:2053: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)
D:\Anaconda3\envs\py36_R\lib\site-packages\sklearn\model_selection\_split.py:2053: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)
D:\Anaconda3\envs\py36_R\lib\site-packages\sklearn\model_selection\_split.py:2053: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)
D:\Anaconda3\envs\py36_R\lib\site-packages\sklearn\model_selection\_split.py:2053: FutureWarning: You should specify a value for 'cv' instead of relying on the default v

In [54]:
def write(file_name, *result):
    with open(file_name, 'w') as file:
        file.write(" ".join(list(map(str, result))))

**Вопрос 1. Каким получилось максимальное качество классификации на датасете breast_cancer?**

In [42]:
write("1.txt", max(result[0]))

**2. Каким получилось максимальное качество классификации на датасете digits?**

In [43]:
write("2.txt", max(result[1]))

**3. Выберите верные утверждения и запишите их номера через пробел (в порядке возрастания номера):**

     1) На вещественных признаках лучше всего сработал наивный байесовский классификатор с распределением Бернулли
    
     2) На вещественных признаках лучше всего сработал наивный байесовский классификатор с мультиномиальным распределением

     3) Мультиномиальное распределение лучше показало себя на выборке с целыми неотрицательными значениями признаков $\large \checkmark$

     4) На вещественных признаках лучше всего сработало нормальное распределение $\large \checkmark$

In [49]:
print(load_breast_cancer()['DESCR'])

.. _breast_cancer_dataset:

Breast cancer wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

    :Number of Instances: 569

    :Number of Attributes: 30 numeric, predictive attributes and the class

    :Attribute Information:
        - radius (mean of distances from center to points on the perimeter)
        - texture (standard deviation of gray-scale values)
        - perimeter
        - area
        - smoothness (local variation in radius lengths)
        - compactness (perimeter^2 / area - 1.0)
        - concavity (severity of concave portions of the contour)
        - concave points (number of concave portions of the contour)
        - symmetry 
        - fractal dimension ("coastline approximation" - 1)

        The mean, standard error, and "worst" or largest (mean of the three
        largest values) of these features were computed for each image,
        resulting in 30 features.  For instance, field 3 is Mean Radius, f

In [52]:
d_data[:1]

array([[ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.,  0.,  0., 13., 15., 10.,
        15.,  5.,  0.,  0.,  3., 15.,  2.,  0., 11.,  8.,  0.,  0.,  4.,
        12.,  0.,  0.,  8.,  8.,  0.,  0.,  5.,  8.,  0.,  0.,  9.,  8.,
         0.,  0.,  4., 11.,  0.,  1., 12.,  7.,  0.,  0.,  2., 14.,  5.,
        10., 12.,  0.,  0.,  0.,  0.,  6., 13., 10.,  0.,  0.,  0.]])

In [55]:
write("3.txt", 3, 4)